/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    D1: typeof import('./components/2023/D1.vue')['default']
    D10: typeof import('./components/2023/D10.vue')['default']
    D11: typeof import('./components/2023/D11.vue')['default']
    D12: typeof import('./components/2023/D12.vue')['default']
    D13: typeof import('./components/2023/D13.vue')['default']
    D14: typeof import('./components/2023/D14.vue')['default']
    D15: typeof import('./components/2023/D15.vue')['default']
    D16: typeof import('./components/2023/D16.vue')['default']
    D2: typeof import('./components/2023/D2.vue')['default']
    D3: typeof import('./components/2023/D3.vue')['default']
    D4: typeof import('./components/2023/D4.vue')['default']
    D5: typeof import('./components/2023/D5.vue')['default']
    D6: typeof import('./components/2023/D6.vue')['default']
    D7: typeof import('./components/2023/D7.vue')['default']
    D8: typeof import('./components/2023/D8.vue')['default']
    D9: typeof import('./components/2023/D9.vue')['default']
    MissingSolutionComponent: typeof import('./components/MissingSolutionComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    V10: typeof import('./components/2023/V10.vue')['default']
    V16: typeof import('./components/2023/V16.vue')['default']
    V3: typeof import('./components/2024/V3.vue')['default']
  }
}
