/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    D1: typeof import('./components/2023/D1.vue')['default']
    D10: typeof import('./components/2023/D10.vue')['default']
    D2: typeof import('./components/2023/D2.vue')['default']
    D3: typeof import('./components/2023/D3.vue')['default']
    D4: typeof import('./components/2023/D4.vue')['default']
    D5: typeof import('./components/2023/D5.vue')['default']
    D6: typeof import('./components/2023/D6.vue')['default']
    D7: typeof import('./components/2023/D7.vue')['default']
    D8: typeof import('./components/2023/D8.vue')['default']
    D9: typeof import('./components/2023/D9.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IBiChevronDoubleLeft: typeof import('~icons/bi/chevron-double-left')['default']
    IBiCircleHalf: typeof import('~icons/bi/circle-half')['default']
    IBiEasel2Fill: typeof import('~icons/bi/easel2-fill')['default']
    IBiExclamationTriangleFill: typeof import('~icons/bi/exclamation-triangle-fill')['default']
    IBiMoonStars: typeof import('~icons/bi/moon-stars')['default']
    IBiPlayFill: typeof import('~icons/bi/play-fill')['default']
    IBiStar: typeof import('~icons/bi/star')['default']
    IBiStarFill: typeof import('~icons/bi/star-fill')['default']
    IBiSunFill: typeof import('~icons/bi/sun-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    V10: typeof import('./components/2023/V10.vue')['default']
  }
}
